'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

test('Operations Center exposes the advanced safety, incident and resilience surfaces', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'src', 'renderer', 'index.html'), 'utf8');
  const app = fs.readFileSync(path.join(__dirname, '..', 'src', 'renderer', 'app.js'), 'utf8');
  for (const marker of ['panel-operations-center', 'Connection Graph', 'Time Machine', 'Incident', 'Offline Vault', 'Break Glass', 'Zero-Trust Gateway', 'Service Map', 'Canary Autopilot', 'Database Studio Pro', 'Replay Lab']) assert.match(html, new RegExp(marker, 'i'));
  for (const marker of ['replaceRollback', 'secretScan', 'anomalyBaseline', 'timeMachineCapture', 'shadowDeploy', 'certificateRenew', 'accessBegin', 'accessApprove', 'fleetRun', 'disasterSimulate', 'evidenceSeal']) assert.match(app, new RegExp(marker));
  for (const marker of ['Universal Terminal Workspace', 'Terminal Intelligence', 'Adaptive Files', 'Fleet &amp; Pair Terminal', 'Replay &amp; Rescue']) assert.match(html, new RegExp(marker, 'i'));
  for (const action of ['universal-connection-workspace', 'command-timeline-undo', 'live-file-collaboration', 'connection-doctor-2', 'smart-transfer-engine', 'workspace-resume', 'secretless-connections', 'fleet-terminal-pro', 'environment-diff-pro', 'disposable-rescue', 'operational-memory', 'visual-ssh-multiplexer', 'infrastructure-movie', 'live-blast-map', 'remote-pair-debugger', 'policy-autocomplete', 'one-click-incident-room', 'network-path-replay', 'portable-rescue-kit', 'intent-command-palette']) { assert.match(html, new RegExp(`data-ops="${action}"`)); assert.match(app, new RegExp(action)); }
  for (const marker of ['Terminal Notebook &amp; Safety', 'Terminal Session Studio', 'Deep Remote Files', 'Remote File Intelligence', 'Context &amp; Transfer Fabric', 'Secure File Exchange', 'Filesystem Watch &amp; Explain']) assert.match(html, new RegExp(marker, 'i'));
  for (const action of ['terminal-notebook', 'secure-paste-firewall', 'shell-dialect-translator', 'terminal-sidecar', 'command-shadow-mode', 'terminal-checkpoint', 'multi-host-result-matrix', 'interactive-output-actions', 'terminal-recording-studio', 'protocol-console', 'transactional-multi-file-editor', 'container-kubernetes-files', 'git-aware-remote-files', 'archive-as-folder', 'huge-file-studio', 'remote-content-index', 'file-provenance', 'cross-protocol-drag-drop', 'duplicate-similarity-finder', 'filesystem-heatmap', 'terminal-file-causality', 'context-aware-split-view', 'transfer-pipeline-builder', 'safe-remote-drop-zone', 'connection-capsule', 'server-airdrop', 'remote-clipboard-vault', 'filesystem-watch-explain']) { assert.match(html, new RegExp(`data-ops="${action}"`)); assert.match(app, new RegExp(action)); }
  for (const feature of ['remote-workspace-drive', 'delta-transfer-engine', 'offline-workspace', 'remote-code-intelligence', 'universal-content-search', 'connection-graph', 'smart-jump-tunnel-manager', 'just-in-time-secrets', 'policy-as-code-guardrails', 'forensic-mode', 'ephemeral-ssh-certificates', 'canary-operations', 'production-safety-lens', 'digital-twin-sandbox', 'intent-terminal', 'collaborative-terminal', 'terminal-heads-up-display', 'visual-permission-studio', 'remote-disaster-undo', 'living-runbooks', 'adaptive-operations-scheduler', 'context-teleport']) { assert.match(html, new RegExp(`data-vision="${feature}"`)); assert.match(app, new RegExp(`'${feature}'`)); }
  for (const feature of ['structured-output-canvas', 'file-relationship-graph', 'signed-transfer-receipts', 'predictive-workspace-cache', 'live-remote-event-stream', 'semantic-file-history', 'visual-batch-rename-transform', 'remote-data-inspector', 'connection-continuity', 'server-identity-trust-timeline', 'reviewable-command-composer', 'terminal-focus-mode', 'universal-staging-area', 'multi-monitor-operations-layout', 'command-file-bookmarks', 'explain-this-screen', 'remote-workspace-health', 'disposable-data-lens']) { assert.match(html, new RegExp(`data-vision="${feature}"`)); assert.match(app, new RegExp(`'${feature}'`)); }
  for (const feature of ['cross-server-command-matrix', 'transfer-control-center', 'direct-server-transfer', 'atomic-remote-editor', 'session-time-machine', 'filesystem-snapshot-diff', 'smart-sync-profiles', 'archive-explorer', 'remote-storage-fabric', 'live-virtual-folders', 'disk-space-visualizer', 'process-port-container-navigator', 'secure-clipboard-bridge', 'shell-resurrection', 'terminal-file-manager-fusion']) { assert.match(html, new RegExp(`data-vision="${feature}"`)); assert.match(app, new RegExp(`'${feature}'`)); }
  for (const feature of ['execution-context-beacon', 'connection-waterfall-tuner', 'data-boundary-guard', 'live-output-privacy-shield', 'detached-job-orchestrator', 'conflict-resolution-cockpit', 'executable-trust-inspector', 'resource-budgeted-commands', 'remote-quarantine-lab', 'branchable-terminal', 'adaptive-ssh-channel-pool', 'terminal-files-review-inbox']) { assert.match(html, new RegExp(`data-vision-context="${feature}"`)); assert.match(app, new RegExp(`'${feature}'`)); }
  for (const feature of ['approved-execution-engine', 'visual-result-renderers', 'unified-remote-session-canvas', 'remote-desktop-quality-engine', 'remote-desktop-file-bridge', 'capability-negotiator', 'optional-kitsune-agent', 'contextual-action-orb', 'terminal-files-adapter-sdk', 'remote-operations-test-lab', 'keyboard-accessibility-pass', 'performance-large-fleet-pass']) { assert.match(html, new RegExp(`data-vision-platform="${feature}"`)); assert.match(app, new RegExp(`'${feature}'`)); }
  for (const feature of ['semantic-shell-layer', 'config-studio', 'identity-trust-center', 'remote-desktop-pro', 'live-process-network-explorer', 'workspace-recovery-capsule', 'cross-host-data-pipeline', 'command-reproducibility', 'disposable-shadow-host', 'focus-incident-layouts']) { assert.match(html, new RegExp(`data-vision-expert="${feature}"`)); assert.match(app, new RegExp(`'${feature}'`)); }
  for (const layer of ['live-session-canvas-engine', 'native-shell-integration', 'production-transfer-core', 'remote-editor-core', 'crash-safe-workspace-journal', 'real-protocol-test-matrix', 'signed-portable-tool-updater', 'connection-broker-2', 'extreme-scale-profiling', 'security-hardening-pass']) assert.match(html, new RegExp(`data-runtime-layer="${layer}"`));
  for (const tab of ['workspace', 'transfer', 'connect', 'safety', 'intelligence', 'team']) assert.match(html, new RegExp(`data-vision-tab="${tab}"`));
  assert.match(html, /tf-vision-inspector/); assert.match(app, /selectVisionFeature/); assert.match(app, /textContent = definition\.title/);
  assert.match(html, /id="tf-vision-search"/); assert.match(app, /filterVisionFeatures/); assert.match(html, /89 capabilities ready/); assert.match(html, /55 workflows/); assert.match(html, /Context workbench/); assert.match(html, /Advanced Labs/); assert.match(html, /Platform Foundation/); assert.match(html, /Expert Workspaces/); assert.match(html, /5 focused modes/); assert.match(html, /Production Runtime/); assert.match(html, /Run production audit/); assert.match(app, /runTerminalFileRuntimeAudit/); assert.match(app, /renderTerminalFileRuntime/); assert.match(html, /tf-review-count/); assert.match(app, /renderVisionResultPreview/); assert.match(html, /Approved Execution/);
  assert.match(html, /Deep Tools Dock/); assert.match(html, /9 context-aware tools/); assert.match(app, /runTerminalFileDeepTool/); assert.match(app, /renderTerminalFileDeepResult/); for (const feature of ['binary-huge-file-workbench', 'metadata-fidelity-engine', 'cloud-object-storage-pro', 'remote-git-workspace', 'hardware-backed-ssh', 'migration-assistant', 'modern-terminal-media', 'real-remote-mounts', 'protocol-compatibility-ci-lab']) assert.match(html, new RegExp(`data-deep-tool="${feature}"`));
  assert.match(html, /@xterm\/addon-image\/lib\/addon-image\.js/); assert.match(app, /registerOscHandler\(52/); assert.match(app, /new ImageAddon\.ImageAddon/);
  assert.match(html, /kitty-graphics\.js/); assert.match(app, /KittyGraphicsRenderer/); assert.match(app, /winfsp-install/); assert.match(app, /index-directory/);
  assert.match(html, /id="fm-command-deck"/); assert.match(html, /id="btn-terminal-command-deck"/); assert.match(app, /selectVisionTab\('workspace'\)/); assert.match(app, /selectVisionTab\('intelligence'\)/);
  assert.match(html, /id="ops-overview"/);
  for (const section of ['start', 'sessions', 'safety', 'automation', 'advanced']) assert.match(html, new RegExp(`data-ops-section="${section}"`));
  assert.match(app, /panel\.dataset\.opsSection = section/);
  assert.match(app, /#ops-section-tabs \[data-ops-section\]/);
  assert.match(app, /overview\.classList\.toggle\('hidden', section !== 'start'\)/);
  assert.match(app, /deck\.classList\.toggle\('hidden', !\['sessions', 'advanced'\]\.includes\(section\)\)/);
});
