'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { TerminalFileDeepManager, CAPABILITIES } = require('../src/terminal-file-deep-manager');

function fixture(options = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'kitsune-deep-')); const sessions = [{ id: 'srv-1', name: 'Server', host: 'host.test', port: 22, username: 'ops', remotePath: '/srv/app', auth: 'key' }];
  const remote = { list: () => sessions, listMounts: () => [], save: input => { const session = { id: `saved-${sessions.length}`, ...input }; sessions.push(session); return { session }; }, mountSftp: (_session, drive) => ({ id: 'mount-1', drive }), unmountSftp: () => ({ success: true }) };
  const ops = { calls: [], async exec(_session, command) { this.calls.push(command); return { success: true, stdout: 'mode=644\nuid=1000\ngid=1000\n', stderr: '' }; } };
  const pro = { async gitFiles(sessionId, input) { return { success: true, sessionId, ...input, mutationsExecuted: false }; } };
  const storage = options.storage || { resolve: input => ({ id: input.id, type: 's3', bucket: 'bucket' }) };
  const manager = new TerminalFileDeepManager(root, { remoteAccess: remote, remoteOperations: ops, terminalFilePro: pro, cloudStorage: storage, allowMount: options.allowMount });
  return { root, manager, remote, ops, sessions };
}

test('deep dock exposes exactly nine contextual capabilities', t => { const { root, manager } = fixture(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const summary = manager.summary(); assert.deepEqual(summary.capabilities, CAPABILITIES); assert.equal(summary.total, 9); assert.equal(summary.features.length, 9); assert.ok(summary.ready >= 6); });

test('binary workbench reads bounded ranges and provides a virtualized hex view', async t => { const { root, manager } = fixture(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const file = path.join(root, 'binary.dat'); fs.writeFileSync(file, Buffer.from([0, 1, 2, 65, 66, 67, 255])); const result = await manager.binaryWorkbench({ path: file, offset: 1, length: 16 }); assert.equal(result.bytesRead, 6); assert.equal(result.range.from, 1); assert.equal(result.virtualized, true); assert.equal(result.fullFileLoaded, false); assert.match(result.hexRows[0].hex, /^01 02 41/); });

test('metadata fidelity inspects local metadata and maps cross-platform losses', async t => { const { root, manager } = fixture(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const file = path.join(root, 'meta.txt'); fs.writeFileSync(file, 'data'); const inspected = await manager.metadataFidelity({ path: file }); assert.equal(inspected.type, 'file'); assert.equal(inspected.mutationsExecuted, false); const matrix = await manager.metadataFidelity({ action: 'matrix', sourcePlatform: 'windows', destinationPlatform: 'linux' }); assert.equal(matrix.fields.length, 10); assert.ok(matrix.fields.some(item => item.fidelity === 'sidecar-required')); });

test('remote Git mutations remain approval gated and are verified', async t => { const { root, manager, ops } = fixture(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const preview = await manager.remoteGit({ sessionId: 'srv-1', root: '/srv/app', file: '/srv/app/a.txt', action: 'stage' }); assert.equal(preview.requiresApproval, true); assert.equal(ops.calls.length, 0); const applied = await manager.remoteGit({ sessionId: 'srv-1', root: '/srv/app', file: '/srv/app/a.txt', action: 'stage', approved: true }); assert.equal(applied.result.success, true); assert.match(ops.calls[0], /git -C/); assert.ok(applied.verified); });

test('migration assistant previews MobaXterm without credentials and skips duplicates', t => { const { root, manager, sessions } = fixture(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const preview = manager.migration({ format: 'mobaxterm', content: '[Bookmarks]\nWeb=#109#%web.test%admin%2222%/srv/www' }); assert.equal(preview.migration.sessions.length, 1); assert.equal(preview.credentialsImported, false); const applied = manager.migration({ action: 'apply', id: preview.migration.id, approved: true }); assert.equal(applied.imported.length, 1); assert.equal(sessions.at(-1).host, 'web.test'); assert.equal(sessions.at(-1).password, undefined); });

test('terminal media blocks OSC 52 by default and never opens links', t => { const { root, manager } = fixture(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const policy = manager.terminalMedia({ action: 'policy', osc52Clipboard: true }); assert.equal(policy.policy.osc52Clipboard, 'ask-every-time'); const data = '\x1b]8;;https://example.test\x07Docs\x1b]8;;\x07\x1b]52;c;' + Buffer.from('secret').toString('base64') + '\x07'; const parsed = manager.terminalMedia({ action: 'parse', data }); assert.equal(parsed.links.length, 1); assert.equal(parsed.clipboard[0].approved, false); assert.equal(parsed.clipboard[0].value, undefined); assert.equal(parsed.externalLinksOpened, false); });

test('cloud multipart uses provider-native Azure blocks and checkpoints progress', async t => { const staged = []; const blob = { async stageBlock(id, _buffer, bytes) { staged.push({ id, bytes }); }, async commitBlockList(ids) { assert.equal(ids.length, staged.length); }, async getProperties() { return { etag: 'verified-etag' }; } }; const storage = { resolve: input => ({ id: input.id, type: 'azure', container: 'files' }), _azure: () => ({ getBlockBlobClient: () => blob }) }; const { root, manager } = fixture({ storage }); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const file = path.join(root, 'large.bin'); fs.writeFileSync(file, Buffer.alloc(10 * 1024 * 1024 + 17, 7)); const preview = await manager.cloudPro({ action: 'multipart-upload', profileId: 'azure-1', localPath: file, key: 'large.bin' }); assert.equal(preview.requiresApproval, true); const result = await manager.cloudPro({ action: 'multipart-upload', profileId: 'azure-1', localPath: file, key: 'large.bin', partSize: 5 * 1024 * 1024, approved: true }); assert.equal(result.job.status, 'completed'); assert.equal(result.job.etag, 'verified-etag'); assert.equal(staged.length, 3); });

test('mount and real protocol lab require explicit approval and never target production', t => { const { root, manager } = fixture({ allowMount: true }); t.after(() => { manager.stopAll(); fs.rmSync(root, { recursive: true, force: true }); }); const mount = manager.realMount({ protocol: 'sftp', sessionId: 'srv-1', mountPoint: 'K:' }); assert.equal(mount.requiresApproval, true); const lab = manager.protocolLab({ run: false }); assert.equal(lab.cells, 81); assert.deepEqual(lab.runnerPlatforms, ['windows', 'linux']); assert.equal(lab.productionTouched, false); assert.equal(lab.disposableOnly, true); assert.ok(fs.existsSync(lab.composeFile)); });

test('scale engine indexes and searches a durable SQLite index off the UI thread', async t => { const { root, manager } = fixture(); t.after(() => { manager.stopAll(); fs.rmSync(root, { recursive: true, force: true }); }); const directory = path.join(root, 'many'); fs.mkdirSync(directory); fs.writeFileSync(path.join(directory, 'alpha.log'), 'a'); fs.writeFileSync(path.join(directory, 'beta.txt'), 'b'); const indexed = await manager.binaryWorkbench({ action: 'index-directory', path: directory }); assert.equal(indexed.result.files, 2); assert.equal(indexed.result.backend, 'sqlite-wal'); const found = await manager.binaryWorkbench({ action: 'search-index', path: directory, query: 'alpha' }); assert.equal(found.count, 1); assert.match(found.rows[0].path, /alpha\.log$/); assert.equal(manager.summary().runtime.scale.workerThreads, true); });

test('WinFsp bootstrap is honest about platform and requires approval before driver changes', t => { const { root, manager } = fixture(); t.after(() => { manager.stopAll(); fs.rmSync(root, { recursive: true, force: true }); }); const status = manager.winFspBootstrap({ action: 'status' }); if (process.platform === 'win32') { const plan = manager.winFspBootstrap({ action: 'install' }); assert.equal(plan.requiresApproval, true); assert.equal(plan.portable, false); assert.equal(plan.requiresElevation, true); } else assert.equal(status.supported, false); });
