'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('fs'); const os = require('os'); const path = require('path'); const WorkspaceSuiteManager = require('../src/workspace-suite-manager');
function fixture(t) { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'kitsune-suite-')); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const values = new Map(); const secretStore = { set: (key, value) => values.set(key, value), get: key => values.get(key) || '', remove: key => values.delete(key) }; return { root, values, manager: new WorkspaceSuiteManager(root, secretStore, { exec: async () => ({ success: true }) }) }; }
test('three-way merge accepts independent edits and marks conflicting edits', t => { const { manager } = fixture(t); assert.deepEqual(manager.merge3('a\nb', 'A\nb', 'a\nB'), { content: 'A\nB', conflicts: 0, clean: true }); const conflict = manager.merge3('a', 'left', 'right'); assert.equal(conflict.conflicts, 1); assert.match(conflict.content, /<<<<<<< LOCAL/); });
test('file snapshots are integrity checked and restorable', t => { const { root, manager } = fixture(t); const file = path.join(root, 'sample.txt'); fs.writeFileSync(file, 'before'); const snapshot = manager.snapshotLocal(file); fs.writeFileSync(file, 'after'); manager.restoreSnapshot(snapshot.id); assert.equal(fs.readFileSync(file, 'utf8'), 'before'); });
test('handoffs contain no password, expire, and can only be consumed once', t => { const { manager } = fixture(t); const created = manager.createHandoff('server-1', 'operator', 30); assert.equal(manager.consumeHandoff(created.handoff.id, created.token).sessionId, 'server-1'); assert.throws(() => manager.consumeHandoff(created.handoff.id, created.token), /invalid|expired/); assert.doesNotMatch(JSON.stringify(manager.listState()), new RegExp(created.token)); });
test('roles, schedules, templates and SDK plugin manifests are validated', t => { const { manager } = fixture(t); manager.saveItem('members', { name: 'Operator', role: 'operator' }); manager.saveItem('schedules', { name: 'Nightly', type: 'backup', sessionId: 'server-1', remotePath: '/srv/archive.tar', intervalHours: 24, encrypted: true }); manager.saveItem('templates', { name: 'Production workspace', panels: ['terminal'] }); manager.saveItem('plugins', { name: 'YAML Preview', pluginId: 'dev.example.yaml', kind: 'preview', permissions: ['filesystem-read', 'invalid'] }); const state = manager.listState(); assert.equal(state.members.at(-1).role, 'operator'); assert.equal(state.schedules[0].encrypted, true); assert.deepEqual(state.plugins[0].permissions, ['filesystem-read']); assert.throws(() => manager.saveItem('members', { name: 'Bad', role: 'root' }), /role/); });

test('due remote backups run, encrypt artifacts and advance the schedule', async t => {
  const { manager } = fixture(t); manager.remote = { list: () => [{ id: 'server-1' }], transferResumable: async (_session, _direction, local) => { fs.mkdirSync(path.dirname(local), { recursive: true }); fs.writeFileSync(local, 'remote backup'); return { success: true, bytes: 13 }; } };
  const saved = manager.saveItem('schedules', { name: 'Due backup', type: 'backup', sessionId: 'server-1', remotePath: '/srv/archive.tar', intervalHours: 1, encrypted: true, nextRunAt: new Date(0).toISOString() }).item;
  const results = await manager.runDue(); assert.equal(results[0].success, true); assert.match(results[0].result.path, /\.enc$/); assert.equal(fs.readFileSync(results[0].result.path).subarray(0, 5).toString(), 'KSSB1'); assert.ok(Date.parse(manager.listState().schedules.find(item => item.id === saved.id).nextRunAt) > Date.now());
});
