<?php

class Modules_KitsuneservBridge_WebServer extends pm_Hook_WebServer
{
    public function getDomainNginxConfig(pm_Domain $domain)
    {
        return $this->directives($domain);
    }

    public function getDomainNginxProxyConfig(pm_Domain $domain)
    {
        return $this->directives($domain);
    }

    private function directives(pm_Domain $domain)
    {
        $config = Modules_KitsuneservBridge_Config::values();
        $name = strtolower(trim((string) $domain->getName()));
        if (($config['proxy_mode'] ?? 'manual') !== 'managed' || !in_array($name, Modules_KitsuneservBridge_Config::proxyDomains($config), true)) return '';
        $port = max(1024, min(65535, (int) ($config['hub_port'] ?: 10000)));
        $apiDomains = array_values(array_diff(Modules_KitsuneservBridge_Config::proxyDomains($config), [(string) ($config['panel_domain'] ?? '')]));
        $namespaceAlias = in_array($name, $apiDomains, true)
            ? "# Każde API Flow używa jednej nazwy pod tą domeną bazową.\nserver_name *." . $name . ";\n"
            : '';
        return "# KitsuneServ Bridge — generated by the Plesk WebServer hook\n"
            . $namespaceAlias
            . "rewrite ^/(?!\\.well-known(?:/|$)|__kitsuneserv_bridge_internal__$).* /__kitsuneserv_bridge_internal__ last;\n\n"
            . "location = /__kitsuneserv_bridge_internal__ {\n"
            . "    internal;\n"
            . "    proxy_pass http://127.0.0.1:" . $port . "\$request_uri;\n"
            . "    proxy_http_version 1.1;\n"
            . "    proxy_set_header Host \$host;\n"
            . "    proxy_set_header X-Real-IP \$remote_addr;\n"
            . "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\n"
            . "    proxy_set_header X-Forwarded-Proto \$scheme;\n"
            . "    proxy_set_header Upgrade \$http_upgrade;\n"
            . "    proxy_set_header Connection \"upgrade\";\n"
            . "    proxy_read_timeout 300s;\n"
            . "    proxy_send_timeout 300s;\n"
            . "    proxy_buffering off;\n"
            . "    client_max_body_size 64m;\n"
            . "}\n";
    }
}
