'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function atomic(file, value) { fs.mkdirSync(path.dirname(file), { recursive: true }); const temp = `${file}.${process.pid}.tmp`; fs.writeFileSync(temp, JSON.stringify(value, null, 2), { mode: 0o600 }); try { fs.renameSync(temp, file); } catch (error) { if (!['EEXIST', 'EPERM'].includes(error.code)) throw error; fs.copyFileSync(temp, file); fs.unlinkSync(temp); } }
function read(file, fallback) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return structuredClone(fallback); } }
function safeText(value, max = 2000) { return String(value || '').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g, '').slice(0, max); }

class IncidentManager {
  constructor(appRoot, secretStore, remoteAccess, remoteOperations, advancedOps, workspaceSuite) { this.root = path.join(path.resolve(appRoot), 'incidents'); this.file = path.join(this.root, 'incidents.json'); this.collabFile = path.join(this.root, 'collaboration.json'); this.secretStore = secretStore; this.remote = remoteAccess; this.ops = remoteOperations; this.advanced = advancedOps; this.suite = workspaceSuite; }
  _all() { return read(this.file, []); }
  _save(items) { atomic(this.file, items.slice(-1000)); return items; }
  list() { return this._all().sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
  hasActive() { return this._all().some(item => item.status === 'active'); }
  async start(input = {}) { const sessions = (input.sessionIds || []).map(id => this.remote.list().find(item => item.id === id)).filter(Boolean); const incident = { id: crypto.randomUUID(), title: safeText(input.title || 'Operational incident', 150), severity: ['sev1', 'sev2', 'sev3', 'sev4'].includes(input.severity) ? input.severity : 'sev2', status: 'active', sessionIds: sessions.map(item => item.id), commander: safeText(input.commander || 'Local owner', 100), createdAt: new Date().toISOString(), endedAt: '', timeline: [], checklist: [{ id: crypto.randomUUID(), text: 'Confirm scope and user impact', done: false }, { id: crypto.randomUUID(), text: 'Preserve evidence before changing state', done: false }, { id: crypto.randomUUID(), text: 'Assign incident commander', done: true }], evidence: [], participants: [] }; incident.timeline.push({ at: incident.createdAt, type: 'incident-started', message: `${incident.severity.toUpperCase()} incident started` }); for (const session of sessions.slice(0, 10)) { try { const diagnosis = await this.remote.diagnose(session); incident.evidence.push({ type: 'diagnostics', sessionId: session.id, capturedAt: new Date().toISOString(), data: diagnosis }); } catch (error) { incident.evidence.push({ type: 'diagnostics-error', sessionId: session.id, capturedAt: new Date().toISOString(), error: error.message }); } } const items = this._all(); items.push(incident); this._save(items); return { success: true, incident };
  }
  update(id, patch = {}) { const items = this._all(); const item = items.find(value => value.id === id); if (!item) throw new Error('Unknown incident'); if (patch.status && ['active', 'monitoring', 'resolved'].includes(patch.status)) { item.status = patch.status; if (patch.status === 'resolved') item.endedAt = new Date().toISOString(); } if (patch.note) item.timeline.push({ at: new Date().toISOString(), type: 'note', author: safeText(patch.author || 'Local owner', 100), message: safeText(patch.note, 4000) }); if (patch.checkId) { const check = item.checklist.find(value => value.id === patch.checkId); if (check) check.done = Boolean(patch.done); } if (patch.checkText) item.checklist.push({ id: crypto.randomUUID(), text: safeText(patch.checkText, 500), done: false }); this._save(items); return { success: true, incident: item }; }
  async collect(id, input = {}) { const items = this._all(); const item = items.find(value => value.id === id); if (!item) throw new Error('Unknown incident'); const session = this.remote.list().find(value => value.id === input.sessionId); if (!session || !item.sessionIds.includes(session.id)) throw new Error('Server is outside incident scope'); if (input.type === 'logs') { const target = String(input.path || '/var/log/syslog'); const result = await this.ops.exec(session, `tail -n ${Math.max(10, Math.min(5000, Number(input.lines) || 500))} -- '${target.replace(/'/g, `'"'"'`)}'`); item.evidence.push({ type: 'logs', sessionId: session.id, path: target, capturedAt: new Date().toISOString(), data: result.stdout.slice(0, 2_000_000) }); } else if (input.type === 'infrastructure') item.evidence.push({ type: 'infrastructure', sessionId: session.id, capturedAt: new Date().toISOString(), data: await this.advanced.captureInfrastructure(session) }); else if (input.type === 'recording') { const recording = this.suite.listRecordings().find(value => value.id === input.recordingId); if (!recording) throw new Error('Unknown recording'); item.evidence.push({ type: 'terminal-recording', recordingId: recording.id, capturedAt: new Date().toISOString(), data: recording }); } else throw new Error('Unsupported evidence type'); item.timeline.push({ at: new Date().toISOString(), type: 'evidence', message: `${input.type} evidence captured for ${session.name}` }); this._save(items); return { success: true, incident: item };
  }
  capsule(id) { const item = this._all().find(value => value.id === id); if (!item) throw new Error('Unknown incident'); const payload = { schemaVersion: 1, exportedAt: new Date().toISOString(), incident: item, integrity: '' }; payload.integrity = crypto.createHash('sha256').update(JSON.stringify(payload.incident)).digest('hex'); fs.mkdirSync(path.join(this.root, 'capsules'), { recursive: true }); const file = path.join(this.root, 'capsules', `${item.id}.capsule.json`); atomic(file, payload); return { success: true, file, integrity: payload.integrity, bytes: fs.statSync(file).size };
  }
  suggestRunbook(id) { const item = this._all().find(value => value.id === id); if (!item) throw new Error('Unknown incident'); const steps = item.timeline.filter(event => ['command', 'action', 'note'].includes(event.type)).map((event, index) => ({ name: `Step ${index + 1}`, command: event.command || `# ${event.message}` })).slice(0, 50); return { name: `${item.title} recovery`, description: `Generated from incident ${item.id}; review every step before saving.`, steps, parameters: [] }; }
  _collab() { return read(this.collabFile, { sessions: [], locks: [], terminalControl: [] }); }
  collaborationStart(input = {}) { const state = this._collab(); const session = { id: crypto.randomUUID(), kind: ['terminal', 'editor', 'war-room'].includes(input.kind) ? input.kind : 'war-room', resourceId: safeText(input.resourceId, 200), owner: safeText(input.owner || 'Local owner', 100), participants: [{ id: 'owner', name: safeText(input.owner || 'Local owner', 100), role: 'controller' }], controlOwner: 'owner', events: [], revision: 0, createdAt: new Date().toISOString(), expiresAt: new Date(Date.now() + Math.max(5, Math.min(1440, Number(input.ttlMinutes) || 120)) * 60000).toISOString() }; state.sessions.push(session); atomic(this.collabFile, state); return { success: true, session };
  }
  collaborationJoin(id, participant = {}) { const state = this._collab(); const session = state.sessions.find(value => value.id === id); if (!session || new Date(session.expiresAt) <= new Date()) throw new Error('Collaboration session expired'); const member = { id: crypto.randomUUID(), name: safeText(participant.name || 'Guest', 100), role: participant.role === 'editor' ? 'editor' : 'observer', joinedAt: new Date().toISOString() }; session.participants.push(member); atomic(this.collabFile, state); return { success: true, member, session }; }
  transferControl(id, participantId, actorId = 'owner') { const state = this._collab(); const session = state.sessions.find(value => value.id === id); if (!session) throw new Error('Unknown collaboration session'); if (session.controlOwner !== actorId && actorId !== 'owner') throw new Error('Only the controller can transfer control'); if (!session.participants.some(item => item.id === participantId)) throw new Error('Unknown participant'); session.controlOwner = participantId; atomic(this.collabFile, state); return { success: true, session }; }
  lockFile(sessionId, filePath, participantId) { const state = this._collab(); const existing = state.locks.find(item => item.sessionId === sessionId && item.filePath === filePath && new Date(item.expiresAt) > new Date()); if (existing && existing.participantId !== participantId) throw new Error('File is locked by another collaborator'); const lock = existing || { id: crypto.randomUUID(), sessionId, filePath: safeText(filePath, 2000), participantId, acquiredAt: new Date().toISOString() }; lock.expiresAt = new Date(Date.now() + 5 * 60000).toISOString(); if (!existing) state.locks.push(lock); atomic(this.collabFile, state); return { success: true, lock }; }
  collaborationEvent(id, participantId, event = {}) { const state = this._collab(); const session = state.sessions.find(value => value.id === id); if (!session || new Date(session.expiresAt) <= new Date()) throw new Error('Collaboration session expired'); const participant = session.participants.find(item => item.id === participantId); if (!participant) throw new Error('Unknown participant'); if (event.kind === 'terminal-input' && session.controlOwner !== participantId) throw new Error('Participant does not control the terminal'); if (event.kind === 'editor-change') { const lock = state.locks.find(item => item.sessionId === id && item.filePath === event.filePath && item.participantId === participantId && new Date(item.expiresAt) > new Date()); if (!lock) throw new Error('An active editor lock is required'); } session.revision += 1; session.events ||= []; session.events.push({ revision: session.revision, participantId, kind: safeText(event.kind, 50), data: safeText(event.data, 32000), filePath: safeText(event.filePath, 2000), at: new Date().toISOString() }); session.events = session.events.slice(-5000); atomic(this.collabFile, state); return { success: true, revision: session.revision }; }
  collaborationEvents(id, since = 0) { const session = this._collab().sessions.find(value => value.id === id); if (!session) throw new Error('Unknown collaboration session'); return { session: { ...session, events: undefined }, events: (session.events || []).filter(item => item.revision > Number(since)).slice(0, 1000), revision: session.revision || 0 }; }
}

module.exports = IncidentManager;
