'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const net = require('net');
const { Transform } = require('stream');
const { spawn, spawnSync } = require('child_process');

function atomic(file, value) { fs.mkdirSync(path.dirname(file), { recursive: true }); const temp = `${file}.${process.pid}.tmp`; fs.writeFileSync(temp, JSON.stringify(value, null, 2), { mode: 0o600 }); try { fs.renameSync(temp, file); } catch (error) { if (!['EEXIST', 'EPERM'].includes(error.code)) throw error; fs.copyFileSync(temp, file); fs.unlinkSync(temp); } }
function read(file, fallback) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return structuredClone(fallback); } }
function tool(name) { const result = spawnSync(process.platform === 'win32' ? 'where.exe' : 'which', [name], { encoding: 'utf8', windowsHide: true }); return result.status === 0 ? result.stdout.split(/\r?\n/)[0].trim() : ''; }
function quote(value) { return `'${String(value).replace(/'/g, `'"'"'`)}'`; }
function safeRemote(value) { const raw = String(value || ''); if (raw.includes('..') || raw.includes('\0')) throw new Error('Unsafe remote path'); const result = path.posix.normalize(raw); if (!result.startsWith('/')) throw new Error('Absolute remote path required'); return result; }

class ResilienceManager {
  constructor(appRoot, secretStore, remoteAccess, remoteOperations) { this.root = path.join(path.resolve(appRoot), 'resilience'); this.secretStore = secretStore; this.remote = remoteAccess; this.ops = remoteOperations; this.cacheRoot = path.join(this.root, 'content-cache'); this.backupRoot = path.join(this.root, 'deduplicated-backups'); this.stateFile = path.join(this.root, 'state.json'); this.mosh = new Map(); }
  capabilities() { return { mosh: Boolean(tool('mosh')), sshKeygen: Boolean(tool('ssh-keygen')), sshKeyscan: Boolean(tool('ssh-keyscan')), openssl: Boolean(tool('openssl')), zstd: Boolean(tool('zstd')) }; }
  createSshCa(name = 'kitsune-ca', passphrase = '') { const id = String(name).replace(/[^A-Za-z0-9_.-]/g, '-').slice(0, 80); const directory = path.join(this.root, 'ssh-ca'); fs.mkdirSync(directory, { recursive: true }); const target = path.join(directory, id); if (fs.existsSync(target)) throw new Error('SSH CA already exists'); const result = spawnSync('ssh-keygen', ['-q', '-t', 'ed25519', '-f', target, '-N', String(passphrase), '-C', id], { encoding: 'utf8', windowsHide: true }); if (result.status !== 0) throw new Error(result.stderr || 'ssh-keygen failed'); if (passphrase) this.secretStore.set(`ssh-ca:${id}:passphrase`, passphrase); return { success: true, id, privatePath: target, publicKey: fs.readFileSync(`${target}.pub`, 'utf8').trim() }; }
  signSshKey(caId, publicKeyPath, identity, principals = [], validity = '+8h') { const ca = path.join(this.root, 'ssh-ca', String(caId)); if (!fs.existsSync(ca)) throw new Error('Unknown SSH CA'); const key = path.resolve(String(publicKeyPath)); if (!fs.existsSync(key) || !key.endsWith('.pub')) throw new Error('Public key file is required'); const safePrincipals = principals.map(value => String(value)).filter(value => /^[A-Za-z0-9_.@-]{1,100}$/.test(value)).slice(0, 20); const args = ['-s', ca, '-I', String(identity).replace(/[^A-Za-z0-9_.@-]/g, '-').slice(0, 100), '-V', String(validity), ...(safePrincipals.length ? ['-n', safePrincipals.join(',')] : []), key]; const env = { ...process.env }; const result = spawnSync('ssh-keygen', args, { encoding: 'utf8', windowsHide: true, env }); if (result.status !== 0) throw new Error(result.stderr || 'SSH certificate signing failed'); return { success: true, certificatePath: key.replace(/\.pub$/, '-cert.pub') }; }
  async installSshCa(connection, caId) { const publicKey = fs.readFileSync(path.join(this.root, 'ssh-ca', `${caId}.pub`), 'utf8').trim(); const encoded = Buffer.from(`${publicKey}\n`).toString('base64'); return this.ops.exec(connection, `umask 077; printf %s ${encoded} | base64 -d | sudo tee /etc/ssh/kitsuneserv_user_ca.pub >/dev/null; sudo sh -c "grep -q '^TrustedUserCAKeys /etc/ssh/kitsuneserv_user_ca.pub$' /etc/ssh/sshd_config || printf '\\nTrustedUserCAKeys /etc/ssh/kitsuneserv_user_ca.pub\\n' >> /etc/ssh/sshd_config"; sudo sshd -t && sudo systemctl reload sshd`); }
  openMosh(connection) { const session = this.remote.resolve(connection); const executable = tool('mosh'); if (!executable) throw new Error('mosh is not installed'); const target = session.username ? `${session.username}@${session.host}` : session.host; const child = spawn(executable, ['--ssh', `ssh -p ${session.port || 22}`, target], { detached: true, stdio: 'ignore', windowsHide: false }); child.unref(); const id = crypto.randomUUID(); this.mosh.set(id, { id, sessionId: session.id, pid: child.pid, startedAt: new Date().toISOString() }); return { success: true, id, pid: child.pid }; }
  async portInspect(connection) { return this.ops.exec(connection, "(ss -lntupH 2>/dev/null || netstat -anp 2>/dev/null); printf '\\n=== DOCKER PORTS ===\\n'; docker ps --format '{{.ID}}\\t{{.Names}}\\t{{.Ports}}' 2>/dev/null"); }
  databaseTunnel(connection, input = {}) { const port = Number(input.remotePort); if (![3306, 5432, 27017, 6379].includes(port) && !(port > 0 && port < 65536)) throw new Error('Invalid database port'); return this.remote.startTunnel(connection, { localPort: Number(input.localPort) || 0, remoteHost: input.remoteHost || '127.0.0.1', remotePort: port }); }
  cron(connection, action, input = {}) { if (action === 'list') return this.ops.exec(connection, 'crontab -l 2>/dev/null || true'); if (action === 'install') { const line = String(input.line || ''); if (line.length > 2000 || /[\r\n\0]/.test(line) || !/^(?:@(?:reboot|hourly|daily|weekly|monthly)|(?:\S+\s+){4}\S+)\s+/.test(line)) throw new Error('Invalid cron entry'); const marker = `kitsuneserv-${crypto.createHash('sha256').update(line).digest('hex').slice(0, 12)}`; return this.ops.exec(connection, `(crontab -l 2>/dev/null | grep -v ${quote(marker)}; printf '%s # %s\\n' ${quote(line)} ${quote(marker)}) | crontab -`); } if (action === 'remove') { const marker = String(input.marker || ''); if (!/^kitsuneserv-[a-f0-9]{12}$/.test(marker)) throw new Error('Invalid cron marker'); return this.ops.exec(connection, `(crontab -l 2>/dev/null | grep -v ${quote(marker)}) | crontab -`); } throw new Error('Unsupported cron action'); }
  systemdTimer(connection, action, input = {}) { const id = String(input.name || '').replace(/[^A-Za-z0-9_.@-]/g, '').slice(0, 80); if (!id) throw new Error('Timer name is required'); if (action === 'status') return this.ops.exec(connection, `systemctl status --no-pager ${quote(id)}.timer`); if (action === 'remove') return this.ops.exec(connection, `sudo systemctl disable --now ${quote(id)}.timer; sudo rm -f /etc/systemd/system/${quote(id)}.timer /etc/systemd/system/${quote(id)}.service; sudo systemctl daemon-reload`); if (action === 'install') { const calendar = String(input.calendar || 'daily'); if (!/^[A-Za-z0-9*:.,_+ -]{1,100}$/.test(calendar)) throw new Error('Invalid OnCalendar expression'); const command = String(input.command || ''); if (!command || command.length > 4000 || /[\r\n\0]/.test(command)) throw new Error('Invalid timer command'); const service = `[Unit]\nDescription=KitsuneServ ${id}\n[Service]\nType=oneshot\nExecStart=/bin/sh -lc ${quote(command)}\n`; const timer = `[Unit]\nDescription=KitsuneServ ${id} timer\n[Timer]\nOnCalendar=${calendar}\nPersistent=true\n[Install]\nWantedBy=timers.target\n`; return this.ops.exec(connection, `printf %s ${Buffer.from(service).toString('base64')} | base64 -d | sudo tee /etc/systemd/system/${id}.service >/dev/null; printf %s ${Buffer.from(timer).toString('base64')} | base64 -d | sudo tee /etc/systemd/system/${id}.timer >/dev/null; sudo systemctl daemon-reload; sudo systemctl enable --now ${id}.timer`); } throw new Error('Unsupported timer action'); }
  firewall(connection, action, rule = {}) { if (action === 'status') return this.ops.exec(connection, `(ufw status numbered 2>/dev/null || firewall-cmd --list-all 2>/dev/null || nft list ruleset 2>/dev/null) | head -n 500`); const port = Number(rule.port); if (!(port > 0 && port < 65536)) throw new Error('Invalid firewall port'); const protocol = rule.protocol === 'udp' ? 'udp' : 'tcp'; const source = rule.source ? String(rule.source) : 'any'; if (!/^(?:any|[A-Fa-f0-9:.]+(?:\/\d{1,3})?)$/.test(source)) throw new Error('Invalid firewall source'); if (!['allow', 'deny', 'delete'].includes(action)) throw new Error('Unsupported firewall action'); const ufw = action === 'delete' ? `sudo ufw --force delete allow from ${source} to any port ${port} proto ${protocol}` : `sudo ufw ${action} from ${source} to any port ${port} proto ${protocol}`; return { preview: ufw, execute: () => this.ops.exec(connection, ufw) }; }
  certificateRenew(connection, provider, domain) { const safeDomain = String(domain || ''); if (!/^(?:\*\.)?[A-Za-z0-9.-]{1,253}$/.test(safeDomain)) throw new Error('Invalid certificate domain'); if (provider === 'certbot') return this.ops.exec(connection, `sudo certbot renew --cert-name ${quote(safeDomain)} --non-interactive`, 300000); if (provider === 'acme.sh') return this.ops.exec(connection, `~/.acme.sh/acme.sh --renew -d ${quote(safeDomain)}`, 300000); if (provider === 'caddy') return this.ops.exec(connection, 'sudo caddy reload --config /etc/caddy/Caddyfile', 120000); throw new Error('Unsupported ACME provider'); }
  cachePut(file) { const source = path.resolve(String(file)); const stat = fs.statSync(source); if (!stat.isFile()) throw new Error('Cache accepts files only'); const digest = crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'); const target = path.join(this.cacheRoot, digest.slice(0, 2), digest); fs.mkdirSync(path.dirname(target), { recursive: true }); const reused = fs.existsSync(target); if (!reused) fs.copyFileSync(source, target); return { success: true, sha256: digest, path: target, size: stat.size, reused }; }
  cacheRestore(digest, target) { if (!/^[a-f0-9]{64}$/.test(digest)) throw new Error('Invalid content hash'); const source = path.join(this.cacheRoot, digest.slice(0, 2), digest); if (!fs.existsSync(source)) throw new Error('Cache object not found'); fs.mkdirSync(path.dirname(path.resolve(target)), { recursive: true }); fs.copyFileSync(source, path.resolve(target)); return { success: true, target: path.resolve(target) }; }
  async transferLimited(connection, direction, localInput, remoteInput, bytesPerSecond = 0) { const local = path.resolve(String(localInput)); const remote = safeRemote(remoteInput); const rate = Math.max(0, Math.min(1024 * 1024 * 1024, Number(bytesPerSecond) || 0)); const throttle = () => { let nextAt = Date.now(); return new Transform({ transform(chunk, _encoding, done) { if (!rate) { this.push(chunk); done(); return; } const delay = Math.max(0, nextAt - Date.now()); nextAt = Math.max(nextAt, Date.now()) + chunk.length / rate * 1000; setTimeout(() => { this.push(chunk); done(); }, delay); } }); };
    if (direction === 'upload') { const cached = this.cachePut(local); const remoteHash = await this.ops.exec(connection, `test -f ${quote(remote)} && sha256sum -- ${quote(remote)} | cut -d' ' -f1 || true`); if (remoteHash.stdout.trim() === cached.sha256) return { success: true, skipped: true, reused: true, sha256: cached.sha256, bytes: cached.size }; }
    const result = await this.remote.withSftp(connection, sftp => new Promise((resolve, reject) => { const source = direction === 'upload' ? fs.createReadStream(local) : sftp.createReadStream(remote); const destination = direction === 'upload' ? sftp.createWriteStream(remote) : fs.createWriteStream(local, { mode: 0o600 }); let bytes = 0; source.on('data', chunk => { bytes += chunk.length; }); source.once('error', reject); destination.once('error', reject); destination.once('close', () => resolve({ success: true, bytes })); source.pipe(throttle()).pipe(destination); })); if (direction === 'download') result.cache = this.cachePut(local); return result; }
  deduplicatedBackup(sourceInput, name = 'backup') { const source = path.resolve(String(sourceInput)); const sourceStat = fs.statSync(source); const files = []; const walk = target => { const stat = fs.statSync(target); if (stat.isDirectory()) for (const child of fs.readdirSync(target)) walk(path.join(target, child)); else { const cached = this.cachePut(target); files.push({ relative: (sourceStat.isFile() ? path.basename(source) : path.relative(source, target)).replace(/\\/g, '/'), sha256: cached.sha256, size: stat.size, mode: stat.mode }); } }; walk(source); const manifest = { id: crypto.randomUUID(), name: String(name).slice(0, 100), source, createdAt: new Date().toISOString(), files, totalBytes: files.reduce((sum, item) => sum + item.size, 0), uniqueObjects: new Set(files.map(item => item.sha256)).size }; const directory = path.join(this.backupRoot, manifest.id); fs.mkdirSync(directory, { recursive: true }); atomic(path.join(directory, 'manifest.json'), manifest); return { success: true, manifest }; }
  restoreDeduplicated(id, targetInput) { const manifest = read(path.join(this.backupRoot, String(id), 'manifest.json'), null); if (!manifest) throw new Error('Unknown backup'); const target = path.resolve(String(targetInput)); fs.mkdirSync(target, { recursive: true }); for (const item of manifest.files) { const destination = path.resolve(target, item.relative); if (destination !== target && !destination.startsWith(`${target}${path.sep}`)) throw new Error('Unsafe backup entry'); this.cacheRestore(item.sha256, destination); } return { success: true, files: manifest.files.length, target }; }
  offlineVaultCreate(input = {}) { if (!input.passphrase || String(input.passphrase).length < 12) throw new Error('Offline Vault requires a passphrase of at least 12 characters'); const payload = { schemaVersion: 1, createdAt: new Date().toISOString(), profiles: input.profiles || [], runbooks: input.runbooks || [], publicKeys: input.publicKeys || [], tools: input.tools || [], secretsIncluded: false }; const salt = crypto.randomBytes(16); const iv = crypto.randomBytes(12); const key = crypto.scryptSync(String(input.passphrase), salt, 32); const cipher = crypto.createCipheriv('aes-256-gcm', key, iv); const encrypted = Buffer.concat([cipher.update(JSON.stringify(payload)), cipher.final()]); const file = path.join(this.root, `offline-vault-${Date.now()}.ksvault`); fs.mkdirSync(this.root, { recursive: true }); fs.writeFileSync(file, Buffer.concat([Buffer.from('KSVLT1'), salt, iv, cipher.getAuthTag(), encrypted]), { mode: 0o600 }); return { success: true, file, bytes: fs.statSync(file).size, secretsIncluded: false }; }
  breakGlassCreate(input = {}) { const state = read(this.stateFile, { breakGlass: [] }); state.breakGlass ||= []; const id = crypto.randomUUID(); const code = crypto.randomBytes(24).toString('base64url'); const record = { id, sessionId: String(input.sessionId || ''), reason: String(input.reason || '').slice(0, 1000), requestedBy: String(input.requestedBy || 'Local owner').slice(0, 100), expiresAt: new Date(Date.now() + Math.max(5, Math.min(60, Number(input.ttlMinutes) || 15)) * 60000).toISOString(), usedAt: '', hash: crypto.createHash('sha256').update(code).digest('hex') }; state.breakGlass.push(record); atomic(this.stateFile, state); return { success: true, id, code, expiresAt: record.expiresAt }; }
  breakGlassConsume(id, code, mfaVerified = false) { if (!mfaVerified) throw new Error('MFA verification is required'); const state = read(this.stateFile, { breakGlass: [] }); const record = state.breakGlass?.find(item => item.id === id); if (!record || record.usedAt || new Date(record.expiresAt) <= new Date()) throw new Error('Break-glass grant is invalid or expired'); const actual = crypto.createHash('sha256').update(String(code)).digest('hex'); if (actual !== record.hash) throw new Error('Invalid break-glass code'); record.usedAt = new Date().toISOString(); atomic(this.stateFile, state); return { success: true, sessionId: record.sessionId, reason: record.reason }; }
}

module.exports = ResilienceManager;
